"""empty message

Revision ID: 5c8141c38154
Revises: 0ec288187fb0
Create Date: 2025-12-17 02:33:06.481218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c8141c38154'
down_revision: Union[str, Sequence[str], None] = '0ec288187fb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('url_queue', sa.Column('is_processed', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('url_queue', 'is_processed')
    # ### end Alembic commands ###
